### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/SpotFire#3]
@ikayz @leemwando we will need to submit if possible let's prep whatever we can to finish this up and submit it the way it is.
We can keep adding more changes once it is uploaded.

**Comment by ikayz** [comment]
@OlivierJM Okay lemme just tweak the UI a bit and Submit push the code.

**Comment by OlivierJM** [comment]
Alright, you can also confirm with Alumanda if the submission process have been made easier, using a snippet link didn't sound useful.

**Comment by ikayz** [comment]
Alright, I'll do that

**Comment by ikayz** [comment]
@OlivierJM seems the submission is still the same, I added a gist though. Failed to do the fiddle one.

**Comment by OlivierJM** [comment]
Thanks for the submitting @ikayz
